receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  attributes:
    actions:
      - key: service.name
        action: insert
        value: "fluent-bit-service"
      - key: log.severity_text
        action: insert
        from_attribute: loglevel
      - key: log.severity_number
        action: insert
        from_attribute: lognum
  batch:
    timeout: 5s
    send_batch_size: 1024

exporters:
  debug:
    verbosity: detailed
  clickhouse:
    endpoint: "http://clickhouse.default.svc.cluster.local:8123"
    database: "default"
    logs_table_name: "otel_logs"
    username: "default"
    password: ""
service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ debug, clickhouse ]
    metrics:
      receivers: [ otlp ]
      exporters: [ debug, clickhouse ]
    logs:
      receivers: [ otlp ]
      processors: [attributes, batch]
      exporters: [ debug, clickhouse ]
