receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
exporters:
  debug:
    verbosity: detailed
  clickhouse:
    endpoint: "http://clickhouse.default.svc.cluster.local:8123"
    database: "default"
    logs_table_name: "otel_logs"
    username: "default"
    password: ""
service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ debug, clickhouse ]
    metrics:
      receivers: [ otlp ]
      exporters: [ debug, clickhouse ]
    logs:
      receivers: [ otlp ]
      exporters: [ debug, clickhouse ]
