deploymentMode: SingleBinary
loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: "s3"
    s3:
      region: ap-south-1
    bucketNames:
      chunks: petclinic-loki-storage
      ruler: petclinic-loki-storage
      admin: petclinic-loki-storage
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        index:
          prefix: loki_index_
          period: 24h
        object_store: s3
        schema: v13
  auth_enabled: false
singleBinary:
  persistence:
    storageClass: gp2
  replicas: 1
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 1
      memory: 1Gi
  extraEnv:
    # Keep a little bit lower than memory limits
    - name: GOMEMLIMIT
      value: 1750MiB
chunksCache:
  resources:
    limits:
      cpu: 1
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
read:
  replicas: 0
backend:
  replicas: 0
write:
  replicas: 0
serviceAccount:
  annotations:
    "eks.amazonaws.com/role-arn": "arn:aws:iam::471112575944:role/petclinic-s3-logs"
