apiVersion: v1
kind: Service
metadata:
  name: otelcol
spec:
  selector:
    app: otelcol
  ports:
    - name: http
      protocol: TCP
      port: 4318
      targetPort: 4318
    - name: grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
