apiVersion: apps/v1
kind: Deployment
metadata:
  name: otelcol
  labels:
    app: otelcol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otelcol
  template:
    metadata:
      labels:
        app: otelcol
    spec:
      containers:
        - name: otelcol
          image: 471112575944.dkr.ecr.ap-south-1.amazonaws.com/otelcol:2
          ports:
            - containerPort: 4318
              name: http
            - containerPort: 4317
              name: grpc
