name: Java CI

on:
  push:
    branches:
      - feat/gh-action
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    uses: infraspecdev/generic-workflows/.github/workflows/maven-ci.yml@main
    with:
      ecr-repository: ${{ vars.ECR_REPOSITORY }}
      aws-region: ${{ vars.AWS_REGION }}
    secrets:
      assume-role: ${{ secrets.CORE_GH_ROLE }}
      gh-token: ${{ secrets.GH_TOKEN }}
